insert into Branch values(1, 'Henry Downtown', '16 Riverview', 10);
insert into Branch values(2, 'Henry On The Hill', '1289 Bedford', 6);
insert into Branch values(3, 'Henry Brentwood', 'Brentwood Mall', 15);
insert into Branch values(4, 'Henry Eastshore', 'Eastshore Mall', 9);

insert into Publisher values('AH', 'Arkham House', 'Sauk City WI');
insert into Publisher values('AP', 'Arcade Publishing', 'New York');
insert into Publisher values('BA', 'Basic Books', 'Boulder CO');
insert into Publisher values('BP', 'Berkley Publishing', 'Boston');
insert into Publisher values('BY', 'Back Bay Books', 'New York');
insert into Publisher values('CT', 'Course Technology', 'Boston');
insert into Publisher values('FA', 'Fawcett Books', 'New York');
insert into Publisher values('FS', 'Farrar Straus and Giroux', 'New York');
insert into Publisher values('HC', 'HarperCollins Publishers', 'New York');
insert into Publisher values('JP', 'Jove Publications', 'New York');
insert into Publisher values('JT', 'Jeremy P. Tarcher', 'Los Angeles');
insert into Publisher values('LB', 'Lb Books', 'New York');
insert into Publisher values('MP', 'McPherson and Co.', 'Kingston');
insert into Publisher values('PE', 'Penguin USA', 'New York');
insert into Publisher values('PL', 'Plume', 'New York');
insert into Publisher values('PU', 'Putnam Publishing Group', 'New York');
insert into Publisher values('RH', 'Random House', 'New York');
insert into Publisher values('SB', 'Schoken Books', 'New York');
insert into Publisher values('SC', 'Scribner', 'New York');
insert into Publisher values('SS', 'Simon and Schuster', 'New York');
insert into Publisher values('ST', 'Scholastic Trade', 'New York');
insert into Publisher values('TA', 'Taunton Press', 'Newton CT');
insert into Publisher values('TB', 'Tor Books', 'New York');
insert into Publisher values('TH', 'Thames and Hudson', 'New York');
insert into Publisher values('TO', 'Touchstone Books', 'Westport CT');
insert into Publisher values('VB', 'Vintage Books', 'New York');
insert into Publisher values('WN', 'W.W. Norton', 'New York');
insert into Publisher values('WP', 'Westview Press', 'Boulder CO');

insert into Author values(1, 'Morrison', 'Toni');
insert into Author values(2, 'Solotaroff', 'Paul');
insert into Author values(3, 'Vintage', 'Vernor');
insert into Author values(4, 'Francis', 'Dick');
insert into Author values(5, 'Straub', 'Peter');
insert into Author values(6, 'King', 'Stephen');
insert into Author values(7, 'Pratt', 'Philip');
insert into Author values(8, 'Chase', 'Truddi');
insert into Author values(9, 'Collins', 'Bradley');
insert into Author values(10, 'Heller', 'Joseph');
insert into Author values(11, 'Wills', 'Gary');
insert into Author values(12, 'Hofstadter', 'Douglas R.');
insert into Author values(13, 'Lee', 'Harper');
insert into Author values(14, 'Ambrose', 'Stephen E.');
insert into Author values(15, 'Rowling', 'J.K.');
insert into Author values(16, 'Salinger', 'J.D.');
insert into Author values(17, 'Heaney', 'Seamus');
insert into Author values(18, 'Camus', 'Albert');
insert into Author values(19, 'Collins, Jr.', 'Bradley');
insert into Author values(20, 'Steinbeck', 'John');
insert into Author values(21, 'Castelman', 'Riva');
insert into Author values(22, 'Owen', 'Barbara');
insert into Author values(23, 'O\'Rourke', 'Randy');
insert into Author values(24, 'Kidder', 'Tracy');
insert into Author values(25, 'Schleining', 'Lon');

insert into Book values('0180', 'A Deepness in the Sky', 'TB', 'SFI', 7.19, true);
insert into Book values('0189', 'Magic Terror', 'FA', 'HOR', 7.99, true);
insert into Book values('0200', 'The Stranger', 'VB', 'FIC', 8.00, true);
insert into Book values('0378', 'Venice', 'SS', 'ART', 24.50, false);
insert into Book values('O79X', 'Second Wind', 'PU', 'MYS', 24.95, false);
insert into Book values('0808', 'The Edge', 'JP', 'MYS', 6.99, true);
insert into Book values('1351', 'Dreamcatcher: A Novel', 'SC', 'HOR', 19.60, false);
insert into Book values('1382', 'Treasure Chests', 'TA', 'ART', 24.46, false);
insert into Book values('138X', 'Beloved', 'PL', 'FIC', 12.95, true);
insert into Book values('2226', 'Harry Potter and the Prison of Azkaban', 'ST', 'SFI', 13.96, false);
insert into Book values('2281', 'Van Gogh and Gauguin', 'WP', 'ART', 21.00, false);
insert into Book values('2766', 'Of Mice and Men', 'PE', 'FIC', 6.95, true);
insert into Book values('2908', 'Electric Light', 'FS', 'POE', 14.00, false);
insert into Book values('3350', 'Group: Six People in Search of a Life', 'BP', 'PSY', 10.40, true);
insert into Book values('3743', 'Nine Stories', 'LB', 'FIC', 5.99, true);
insert into Book values('3906', 'The Soul of a New Machine', 'BY', 'SCI', 11.16, true);
insert into Book values('5163', 'Travels with Charley', 'PE', 'TRA', 7.95, true);
insert into Book values('5790', 'Catch-22', 'SC', 'FIC', 12.00, true);
insert into Book values('6128', 'Jazz', 'PL', 'FIC', 12.95, true);
insert into Book values('6328', 'Band of Brothers', 'TO', 'HIS', 9.60, true);
insert into Book values('669X', 'A Guide to SQL', 'CT', 'CMP', 37.95, true);
insert into Book values('6908', 'Franny and Zooey', 'LB', 'FIC', 5.99, true);
insert into Book values('7405', 'East of Eden', 'PE', 'FIC', 12.95, true);
insert into Book values('7443', 'Harry Potter and the Goblet of Fire', 'ST', 'SFI', 18.16, false);
insert into Book values('7559', 'The Fall', 'VB', 'FIC', 8.00, true);
insert into Book values('8092', 'Godel, Escher, Bach', 'BA', 'PHI', 14.00, true);
insert into Book values('8720', 'When Rabbit Howls', 'JP', 'PSY', 6.29, true);
insert into Book values('9611', 'Black House', 'RH', 'HOR', 18.81, false);
insert into Book values('9627', 'Song of Solomon', 'PL', 'FIC', 14.00, true);
insert into Book values('9701', 'The Grapes of Wrath', 'PE', 'FIC', 13.00, true);
insert into Book values('9882', 'Slay Ride', 'JP', 'MYS', 6.99, true);
insert into Book values('9883', 'The Catcher in the Rye', 'LB', 'FIC', 5.99, true);
insert into Book values('9931', 'To Kill a Mockingbird', 'HC', 'FIC', 18.00, false);

insert into Wrote values(1, '0180', 3, 1);
insert into Wrote values(2, '0189', 5, 1);
insert into Wrote values(3, '0200', 18, 1);
insert into Wrote values(4, '0378', 11, 1);
insert into Wrote values(5, '079X', 4, 1);
insert into Wrote values(6, '0808', 4, 1);
insert into Wrote values(7, '1351', 6, 1);
insert into Wrote values(8, '1382', 23, 2);
insert into Wrote values(9, '1382', 25, 1);
insert into Wrote values(10, '138X', 1, 1);
insert into Wrote values(11, '2226', 15, 1);
insert into Wrote values(12, '2281', 9, 12);
insert into Wrote values(13, '2281', 19, 1);
insert into Wrote values(14, '2766', 20, 1);
insert into Wrote values(15, '2908', 17, 1);
insert into Wrote values(16, '3350', 2, 1);
insert into Wrote values(17, '3743', 16, 1);
insert into Wrote values(18, '3906', 24, 1);
insert into Wrote values(19, '5163', 20, 1);
insert into Wrote values(20, '5790', 10, 1);
insert into Wrote values(21, '6128', 1, 1);
insert into Wrote values(22, '6328', 14, 1);
insert into Wrote values(23, '669X', 7, 1);
insert into Wrote values(24, '6908', 16, 1);
insert into Wrote values(25, '7405', 20, 1);
insert into Wrote values(26, '7443', 15, 1);
insert into Wrote values(27, '7559', 18, 1);
insert into Wrote values(28, '8092', 12, 1);
insert into Wrote values(29, '8720', 8, 1);
insert into Wrote values(30, '9611', 5, 2);
insert into Wrote values(31, '9611', 6, 1);
insert into Wrote values(32, '9627', 1, 1);
insert into Wrote values(33, '9701', 20, 1);
insert into Wrote values(34, '9882', 4, 1);
insert into Wrote values(35, '9883', 16, 1);
insert into Wrote values(36, '9931', 13, 1);

insert into Inventory values(1, '0180', 1, 2);
insert into Inventory values(2, '0189', 2, 2);
insert into Inventory values(3, '0200', 1, 1);
insert into Inventory values(4, '0200', 2, 3);
insert into Inventory values(5, '0378', 3, 2);
insert into Inventory values(6, '079X', 2, 1);
insert into Inventory values(7, '079X', 3, 2);
insert into Inventory values(8, '079X', 4, 3);
insert into Inventory values(9, '0808', 2, 1);
insert into Inventory values(10, '1351', 2, 4);
insert into Inventory values(11, '1351', 3, 2);
insert into Inventory values(12, '1382', 2, 1);
insert into Inventory values(13, '138X', 2, 3);
insert into Inventory values(14, '2226', 3, 2);
insert into Inventory values(15, '2226', 4, 1);
insert into Inventory values(16, '2281', 4, 3);
insert into Inventory values(17, '2766', 3, 2);
insert into Inventory values(18, '2908', 1, 3);
insert into Inventory values(19, '2908', 4, 1);
insert into Inventory values(20, '3350', 1, 2);
insert into Inventory values(21, '3743', 2, 1);
insert into Inventory values(22, '3906', 2, 1);
insert into Inventory values(23, '3906', 3, 2);
insert into Inventory values(24, '5163', 1, 1);
insert into Inventory values(25, '5790', 4, 2);
insert into Inventory values(26, '6128', 2, 4);
insert into Inventory values(27, '6128', 3, 3);
insert into Inventory values(28, '6328', 2, 2);
insert into Inventory values(29, '669X', 1, 1);
insert into Inventory values(30, '6908', 2, 2);
insert into Inventory values(31, '7405', 3, 2);
insert into Inventory values(32, '7443', 4, 1);
insert into Inventory values(33, '7559', 2, 2);
insert into Inventory values(34, '8092', 3, 1);
insert into Inventory values(35, '8720', 1, 3);
insert into Inventory values(36, '9611', 1, 2);
insert into Inventory values(37, '9627', 3, 5);
insert into Inventory values(38, '9627', 4, 2);
insert into Inventory values(39, '9701', 1, 2);
insert into Inventory values(40, '9701', 2, 1);
insert into Inventory values(41, '9701', 3, 3);
insert into Inventory values(42, '9701', 4, 2);
insert into Inventory values(43, '9882', 3, 3);
insert into Inventory values(44, '9883', 2, 3);
insert into Inventory values(45, '9883', 4, 2);
insert into Inventory values(46, '9931', 1, 2);